apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  #annotations:
    #volume.beta.kubernetes.io/storage-class: gp2
spec:
  storageClassName: standard
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi