apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    app.kubernetes.io/name: mongo
    app.kubernetes.io/component: backend
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app.kubernetes.io/name: mongo
    app.kubernetes.io/component: backend
  #type: LoadBalancer