apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-storage
  annotations:
    volume.beta.kubernetes.io/storage-class: gp2
spec:
  storageClassName: local-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi