apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-hp-pvc
  #annotations:
    #volume.beta.kubernetes.io/storage-class: gp2
spec:
  storageClassName: localstorage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi