apiVersion: v1
kind: Pod
metadata:
  name: webapp-env-from-secret
spec:
  containers:
  - image: mmumshad/simple-webapp-color
    name: html-generator
    env:
    - name: secretclr
      ValueFrom:
        secretKeyRef:
          name: my-webapp-secret
          key: APP_COLOR
    volumeMounts:
    - name: html
      mountPath: /var/htdocs
    ports:
    - containerPort: 80
      protocol: TCP
  volumes:
  - name: html
    emptyDir: {}

